minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@verdaccio/*'
  - 'verdaccio-*'
saveExact: true
ignoreScripts: true
preferFrozenLockfile: true
ignoredBuiltDependencies:
  - cypress
  - unrs-resolver
